# Generated by Django 4.2.1 on 2023-05-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_ds_al", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("content", models.CharField(max_length=64)),
                ("user", models.CharField(max_length=32)),
            ],
        ),
    ]
