# Generated by Django 4.2.1 on 2023-05-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_ds_al", "0002_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="content",
            field=models.CharField(max_length=64, verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="notes",
            name="title",
            field=models.CharField(max_length=32, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="notes",
            name="user",
            field=models.CharField(max_length=32, verbose_name="用户"),
        ),
    ]
